[project]
name = "graph-audio"
version = "0.2.0"
description = "Given a lossless audio format (flac or wav), it will plot the pressure waves in the time domain, and frequency components in the frequency domain."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "tqdm>=4.67.3",
]

[project.scripts]
graph_audio = "graph_audio.main:main"
